
#ifndef _QUOTES_H
#define _QUOTES_H

#include <string>
using namespace std;
const char* Quotes[] = {
"An idle youth, a needy age.",
"Time flies.", 
"Time is money.", 
"Time and tide wait for no man.", 
"Time tries all.", 
"Time tries truth.", 
"Time past cannot be called back again.", 
"All time is no time when it is past.", 
"No one can call back yesterday;Yesterday will not be called again.", 
"Tomorrow comes never.", 
"One today is worth two tomorrows.", 
"The morning sun never lasts a day.", 
"Christmas comes but once a year.", 
"Pleasant hours fly past.", 
"Happiness takes no account of time.", 
"Time tames the strongest grief.", 
"The day is short but the work is much.", 
"Never deter till tomorrow that which you can do today.", 
"Have you somewhat to do tomorrow, do it today.",
"To him that does everything in its proper time,  one day is worth three.",
"To save time is to lengthen life.", 
"Everything has its time and that time must be watched.", 
"Take time when time cometh, lest time steal away.",
"When an opportunity is neglected, it never comes back to you.",
"Make hay while the sun shines.", 
"Strike while the iron is hot.", 
"Work today, for you know not how much you may be hindered tomrrow.",
"Punctuality is the soul of business.", 
"Procrastination is the thief of time.", 
"Every tide hath ist ebb.", 
"Knowledge is power.", 
"Wisdom is more to be envied than riches.", 
"Wisdom is better than gold or silver.", 
"Wisdom in the mind is better than money in the hand.", 
"Wisdom is a good purchase though we pay dear for it.", 
"Doubt is the key of knowledge.", 
"If you want knowledge, you must toil for it.",
"A little knowledge is a dangerous thing.", 
"A handful of common sense is worth a bushel of learning.", 
"Knowledge advances by steps and not by leaps.", 
"Learn wisdom by the follies of others.", 
"It is good to learn at another man's cost.", 
"Wisdom is to the mind what health is to the body.", 
"Experience is the best teacher.", 
"Experience is the father of wisdom and memory the mother.", 
"Dexterity comes by experience.", 
"Practice makes perfect.", 
"Experience keeps a dear school, but fools learn in no other.",
" Experience without learning is better than learning without experience.", 
"Wit once bought is worth twice taught.", 
"Seeing is believing.", 
"Business is the salt of life.", 
"Business before pleasure.", 
"Business makes a man as well as tries him.", 
"Business neglected is business lost.", 
"Never think yourself above business.", 
"Business may be troublesome, but idleness is pernicious.",
"He that thinks his business below him will always be above his business.", 
"Do business, but be not a slave to it.",
"Everybody's business is nobody's business.", 
"Work makes the workman.", 
"Better master one than engage with ten.", 
"A work ill done must be twice done.", 
"They who cannot do as they would, must do as they can.",
"If you would have a thing well done, do it yourself.",
"He that doth most at once doth least.", 
"Do as most men do and men will speak well of thee.", 
"What may be done at any time will be done at no time.", 
"Better late than never.", 
"Whatever is worth doing at all is worth doing well.", 
"The shortest answer is doing the thing.", 
"Action is the proper fruit of knowledge.", 
"Finished labours are pleasant.", 
"It is lost labour to sow where there is no soil.", 
"It is right to put everything in its proper use.", 
"Affairs that are done by due degrees are soon ended.", 
"All work and no play makes Jack a dull boy.", 
"Work bears witness who does well.", 
"It is not work that kills, but worry.",
"He that will not work shall not eat.", 
"Business is business.", 
"Deliberate slowly, execute promptly.",
"Put your shoulder to the wheel.", 
"Never do things by halves.", 
"In for a penny, in for a pound.",
"Many hands make quick work.", 
"Many hands make light work.", 
"A bad workman quarrels with his tools.", 
"Diligence is the mohter of success.", 
"Idleness is the root of all evil.", 
"Care and diligence bring luck.", 
"Diligence is the mother of good fortune.", 
"Industry is fortune's right hand, and frugality her left.",
"Idleness is the key of beggary.", 
"No root, no fruit.",
"Idle people (folks) have the most labour (take the most pains).", 
"Sloth is the key of poverty.", 
"Sloth turneth the edge of wit.", 
"An idle brain is the devil's workshop.", 
"The secret of wealth lieth in the letters SAVE.", 
" Lying is the first step to the gallows.", 
"Waste not, want not.",
" From saving comes having.", 
" A penny saved is a penny gained.", 
" Take care of the pence and the pound will take care of themselves.", 
" Frugality is an estate alone.", 
" He that regards not a penny, will lavish a pound.",
" Small gains bring great wealth.", 
" Many a little makes a mickle.", 
" As the touchstone tries gold, so gold tries man.",
"Courage and resolution are the spirit and soul of virtue.", 
"The path to glory is always rugged.", 
"Nothing is difficult to the man who will try.", 
"The fire is the test of gold;adversity of strong man.", 
"Great hopes make great man.", 
"No way is impossible to courage.", 
"A smooth sea never made a skillful mariner.", 
"The good seaman is known in bad weather.", 
"The best hearts are always the bravest.", 
"We must not lie down, and cry,God help us.",
"He that falls today may be up again tomorrow.", 
"Rome was not built in a day.", 
"Success belongs to the persevering.", 
"We must repeat a thousand and one times that perseverance is the only road to success.", 
"Perseverance is failing nineteen times and succeeding the twentieth.", 
"Step by step the ladder is ascended.", 
"Adversity leads to prosperity.", 
"Patience and application will carry us through.", 
"Fortune often rewards with interest those that have patience to wait for her.", 
"All things will come round to him who will but wait.", 
"Constant dropping wears the stone.", 
"Omelets are not made without breaking of eggs.", 
"The world is a ladder for some to go up and others to go down.", 
"There needs a long apprenticeship to understand the mystery of the world's trade.", 
"Life is sweet.", 
"Where there is life, there is hope.",
"Life is not all beer and skittles.", 
"Much water runs by the mill that the miller knows not of.", 
"Fortune knocks once at least at every man's door.", 
"If you are too fortunate,  you will not know yourself; if you are too unfortunate, nobody will know y",
"Every man is the architect of his own fortune.", 
"Happy is he who knows his follies in his youth.", 
"Misfortunes never (seldom) come alone (single).", 
"Misfortune is a good teacher.", 
"Misfortunes come at night.", 
"Misfortunes tell us what fortune is.", 
"Adversity makes a man wise, not rich.",
"Live and learn.", 
"It is never too old to learn.", 
"A man becomes learned by asking questions.", 
"There is no royal road to learning.", 
"He who is ashamed of asking is ashamed of learning.", 
"What is learned in the cradle lasts till the grave.", 
"Learning makes a good man better and ill man worse.", 
"Soon learnt, soon forgotten.",
"Learn young, learn fair.",
"A lazy youth, a lousy age.",
"He that knows nothing, doubts nothing.",
"A good name keeps its luster in the dark.", 
"Fame is a magnifying glass.", 
"A good fame is better than a good face.", 
"Fame like a river is narrowest at its source and broadest afar off.", 
"Take honour from me and my life is done.", 
"Beware of him who regards not his reputation.", 
"It is better to die with honour than to live in infamy.", 
"Adversity successfully overcome is the highest glory.", 
"Reputation is often got without merit and lost without fault.", 
"Your father's honour is to you but a second-hand honour.", 
"Never trust another what you should do yourself.", 
"It is an equal failing to trust everybody, and to trust nobody.",
"Eat a peck of salt with a man before you trust him.", 
"If you trust before you try, you may repent before you die.",
"Never trust to fine words.", 
"Trust not a great weight to a slender thread.", 
"Be just to all, but trust not all.",
"Trust thyself only, and another shall not betray thee.",
"Self-trust is the essence of heroism.", 
"Confidence is a plant of slow growth.", 
"Truth is the daughter of time.", 
"Truth hath a good face, but ill clothes.",
"Truth and roses have thorns about them.", 
"Truth may be blamed, but shall never be shamed.",
"Though malice may darken truth, it cannot put it out.",
"Truth will prevail.", 
"Truth's best ornament is nakedness.", 
"Facts are stubborn things.", 
"Sooner or later, the truth comes to light.",
"The truths we least like to hear are those which it is most to our advantage to know.", 
"Falsehood like a nettle stings those who meddle with it.", 
"There is many a fair thing full false.", 
"Though a lie be well drest, it is ever overcome.",
"A lie begets a lie till they come to generations.", 
"A false tongue will hardly speak truth.", 
"False with one can be false with two.", 
"He that will lie will steal.", 
"Gossiping and lying go together.", 
"Equivocation is first cousin to a lie.", 
"A great talker is a great liar.", 
"The greatest liars talk most of themselves.", 
"Lying rides upon debt's back.", 
" All is not gold that glitters.", 
" Money is the root of evil.", 
" Money makes the mare go.", 
" All things are obedient to money.", 
" Before gold, even kings take off their hats.",
" Money is the key that opens all doors.", 
" Beauty is potent, but money is more potent.",
" Avarice increases with wealth.", 
" The money the miser hoards will do him no good.", 
" What is wealth good for, If it brings melancholy?",
"Gold will not buy anything.", 
"The chief aim of man is not to get money.", 
"Those who believe money can do everything are frequently prepared to do everything for money.", 
"Wealth makes worship.", 
"Little wealth, little care.",
"A moneyless man goes fast through the market.", 
"Poverty is not a crime.", 
"Poverty is not a disgrace, but theft is a disgrace.",
"Better be poor than wicked.", 
"Poverty is not a sufficient cause for disgrace,  but poverty without resolution to help oneself, is a",
"Poverty is the mother of health.", 
"Be considerate toward the poor.", 
"Poor and content is rich and rich enough.", 
"Poverty parteth fellowship.", 
"Poverty makes a man mean.", 
"Nothing to be got without pains but poverty.", 
"Do not through fear of poverty surrender liberty.", 
"Poverty and love are hard to hide.", 
"Poverty breeds strife.", 
"The poor man wants much, the miser everything.",
"The dainties of the great are the tears of the poor.", 
"Poverty on an old man's back is a heavy burden.", 
"Beggars must (should) be no choosers.", 
"A lamb is as dear to a poor man as an ox to the rich.", 
"A light purse makes a heavy heart.", 
"Poor without debt is better than a prince.", 
"Happy is he who owes nothing.", 
"Money borrowed is soon sorrowed.", 
"He that goes a borrowing, goes a sorrowing.",
"Better go to bed supperless than rise in debt.", 
"Out of debt, out of danger.",
"A pound of care will not pay an ounce of debt.", 
"He is the wisest man who does not think himself so.", 
"Wise men have their mouth in their heart, fools their heart in their mouth.",
"Wise men learn by other men's mistakes;fools by their own.", 
"He is wise that knows when he's well enough.", 
"A wise man cares not for what he cannot have.", 
"He is wise that hath wit enough for his own affairs.", 
"No man is born wise.", 
"A wise man will make tools of what comes to hand.", 
"A word is enough to the wise.", 
"He is the wise man who is the honest man.", 
"A wise man thinks all that he says, a fool says all that he thinks.",
"The wise hand doth not all that the foolish mouth speaks.", 
"A flow of words is no proof of wisdom.", 
"It is easy to be wise after the event.", 
"The wise man knows he knows nothing, the fool thinks the knows all.",
"Fools learn nothing from wise men;but wise men learn much from fools.", 
"A fool always comes short of his reckoning.", 
"A fool's heart dances on his lips.", 
"A fool always finds a greater fool than himself.", 
"A man may talk like a wise man and yet act like a fool.", 
"The more riches a fool hath, the greater fool he is.",
"Never challenge a fool to do wrong.", 
"It is better to please a fool than to anger him.", 
"He is a fool who cannot be angry, but he is a wise man who will not.",
"'Tis altogether vain to learn wisdom and yet live foolishly.", 
"Wit without learning is like a tree without fruit.", 
"No man is wise at all times.", 
"Many heads are better than one.", 
"Virtue never grows old.", 
"Virtue is the only true nobility.", 
"Virtue is a jewel of great price.", 
"He that soweth virtue shall reap fame.", 
"To be virtuous is to do good.", 
"Glory is the shadow of virtue.", 
"There is no virtue that poverty destroyeth not.", 
"The first step to virtue is to abstrain from vice.", 
"No good building without a good foundation.", 
"One good turn deserves another.", 
"He that returns good for evil obtains the victory.", 
"We should never remember the benefits we have offered nor forget the favor received.", 
"If they say you are good, ask yourself if it be true.",
"He who avoids temptation avoids the sin.", 
"A quiet conscience sleeps in thunder.", 
"Never be weary of well doing.", 
"Of evil grain, no good seed can come.",
"That which is evil is soon learnt.", 
"No vice goes alone.", 
"An evil lesson is soon learned.", 
"A bad thing never dies.", 
"Evil comes to us by ells and goes away by inches.", 
"The maintaining of one vice costs more than ten virtues.", 
"They that do nothing learn to do ill.", 
"A wicked man is his own hell.", 
"Those who eat best and drink best often do worst.", 
"He who has done ill once will do it again.", 
"There is no going heaven in a sedan.", 
"An ill life, an ill end.",
"A wilful fault has no excuse and deserves no pardon.", 
" Zeal without knowledge is fire without light.", 
" Pardoning the bad is injuring the good.", 
" The evil wound is cured but not the evil name.", 
" Evil communications corrupt good manners.", 
" No wrong without remedy.", 
" Virtue flies from the heart of a mercenary man.", 
" First think, and then speak.",
" A word spoken is past recalling(The words once spoken can never be recalled).", 
" While the word is in your mouth,  it is your own; when 'tis once spoken, 'tis another's.",
" Speech is silver, silence is gold.",
"Few words are best.", 
"No wisdom like silence.", 
"Least said, soonest mended.",
"Second thoughts are best.", 
"Look before you leap.", 
"He is a wise man who speaks little.", 
"Fair words butter no parsnips.", 
"The tongue is not made of steel, yet it cuts.",
"Sometimes words hurt more than swords.", 
"A good tongue is a good weapon.", 
"A wise head makes a close mouth.", 
"It is one thing to speak much and another to speak pertinently.", 
"Unprofitable eloquence is like the cypress, which is great and tall, but bears no fruit.",
"Better say nothing than nothing to the purpose.", 
"Many a true word is spoken in jest.", 
"Few words, many deeds.",
"Actions speak louder than words.", 
"From words to deeds is a great space.", 
"Deeds, not words.",
"Bare words, no bargain.",
"Deeds are fruits, words are but leaves.",
"Ill deeds cannot honour.", 
"Fine words dress ill deeds.", 
"Good words and ill deeds deceive wise and fools.", 
"Our own actions are our security, not others' judgements.",
"A man of words and not deeds is like a garden full of weeds.", 
"A man is not good or bad for one action.", 
"A man apt to promise is apt to forget.", 
"A man that breaks his word, bids others to be false to him.",
"Easier said than done.", 
"The greatest talkers are always the least doers.", 
"The proof of the pudding is in the eating.", 
"Pride goes before a fall.", 
"Pride goes before destruction.", 
"Pride goeth before, and shame cometh after.",
"Pride and grace dwelt never in one place.", 
"He that climbs high falls heavily.", 
"Pride must be pinched.", 
"The more noble the more humble.", 
"Humility often gains more than pride.", 
"He who imagines that he has knowledge enough has none.", 
"No man is the worst for knowing the worst of himself.", 
"Pride may lurk under a threadbare cloak.", 
"It is not a sign of humility to declaim against pride.", 
"He that is full of himself is very empty.", 
"Honesty is the best policy.", 
"An honest man's word is as good as his bond.", 
"Poor but honest.", 
"Honesty may be dear bought, but can never be an ill pennyworth.",
"Knavery may serve, but honesty is best.",
"Every man has his weak side.", 
"He who has no shame has no conscience.", 
"An honest look covereth many faults.", 
"Once a knave, ever a knave.",
"A crafty knave needs no broker.", 
"The honest penny is better than the stolen dollar.", 
"One penny with right is better than a thousand without right.", 
"The unrighteous penny corrupts the righteous pound.", 
"Love is blind.", 
"Love is without reason.", 
"Love is full of trouble.", 
"Love cannot be compelled.", 
"Love begets love.", 
"Love needs no teaching.", 
"Love at first sight.", 
"Love asks faith, and faith firmness.",
"Love is the touchstone of virtue.", 
"Love not at the first look.", 
"Hasty love, soon cold.",
"Love is a sweet torment.", 
"Love rules his kingdom without a sword.", 
"Love will find out the way.", 
"Love is not to be found in the market.", 
"Lovers live by love, as larks live by leeks.",
"Old love will not be forgotten.", 
"True love kythes(=shows itself)in time of need.", 
"Sound love is not soon forgotten.", 
"The greatest hate springs from the greatest love.", 
"No love is foul, nor prison fair.",
"Labour is lihgt where love doth pay.", 
"Love is the reward of love.", 
"Love makes all hard hearts gentle.", 
"When love puts in, friendship is gone.",
"The course of true love never did run smooth.", 
"Love is a sweet tyranny,  because the lover endures his torment willingly.",
"True love is giving, not taking.",
"Love makes obedience easy.", 
"Love is sweet in the beginning, but sour in the end.",
"Where love fails, we espy all faults.",
"Follow love and it will flee, flee love and it will follow thee.",
" When poverty comes in at the door, love flies out of the window.",
" Faults are thick while love is thin.", 
" Hatred is blind as well as love.", 
" Marriage is a lottery.", 
" Marry thy like.", 
" Marriage makes or mars a man.", 
" It is good to marry late or never.", 
" Early wed, early dead.",
" They that marry in green, their sorrow is soon seen.",
" A young man married is a man that's marred.", 
"Marry in haste, and repent at leisure.",
"Marry in lent, and you'll live to repent.",
"He that marries for wealth, sells his liberty.",
"An ill marriage is a spring of ill fortune.", 
"Who marrieth for love without money, hath good nights and sorry days.",
"If you always say \"NO\", never be married.",
"Honest men marry soon, wise men not at all.",
"A good wife and health is a man's best wealth.", 
"A good wife makes a good husband.", 
"Choose a wife rather by your ear than your eye.", 
"Better be half hanged than ill wed.", 
"He who does not honour his wife, dishonours himself.",
"The calmest husbands make the stormiest wives.", 
"It is a sad house where the hen crows louder than the cock.", 
"The wife is the key of the house.", 
"The more women look in their glass, the less they look to their house.",
"East or west, home is best.",
"One father can support ten children; ten children cannot support one father.", 
"One father is more than a hundred school-masters.", 
"Like father, like son.",
"The father buys, the son bigs,the grandchild sells,and his son thigs.",
"The mother's breath is aye sweet.", 
"Like mother, like daughter.",
"Children are the parents' riches.", 
"A little child is the sweetest and purest thing in the world.", 
"He that hath no children, knows not what is love.",
"Children learn to creep ere they can go.", 
"Silly(=good) child is soon ylered(=taught).", 
"Boys will be boys.", 
"One boy is more trouble than a dozen girls.", 
"Spare the rod and spoil the child.", 
"Naughty boys sometimes make good men.", 
"The child is father of the man.", 
"Happy is he that is happy in childhood.", 
"Children and fools cannot lie.", 
"My son is my son till he hath got him a wife,  but my daughter's my daughter all the days of her life",
"It is harder to marry a daughter well than to bring her up well.", 
"A maid that laughs is half taken.", 
"A maiden with many wooers often chooses the worst.", 
"Maids want nothing but husbands, but when they have them they want everything.",
"Would you know your daughter, see her in company.",
"He that would the daughter win, must with the mother first begin.",
"Life without friend is death.", 
"Without a friend, the world is wilderness.",
"Friendless is the dead.", 
"A good friend is my nearest relation.", 
"A near friend is better than a fardwelling kinsman.", 
"A friend to everybody is a friend to nobody.", 
"In time of prosperity, friends will be plenty.",
"It is good to have friends in trouble.", 
"Prosperity makes friends and adversity tries them.", 
"A friend in need is a friend indeed.", 
"Poverty tries friends.", 
"Try your friend ere you trust him.", 
"Prove thy friend ere thou have need.", 
"A friend is never known till a man have need.", 
"A faithful friend is hard to find.", 
"Friends are like fiddle-strings, they must not be screwed too tight.",
"Have but few frieds, though many acquaintances.",
"All are not friends that speak us fair.", 
"He that hath a full purse never wanted a friend.", 
"A friend in court is better than a penny in purse.", 
"It is good to have some friends both in heaven and hell.", 
"We shall never have friends if we expect to find them without fault.", 
"A friend without faults will never be found.", 
"A man without a friend is only half a man.", 
"A friend is not so soon gotten as lost.", 
"Friendship cannot stand always on one side.", 
"Old acquaintance will soon be remembered.", 
"He is a good friend that speaks well of us behind our backs.", 
"Friends (the best of friends) must part.", 
"A friend is best found in adversity.", 
"I will be thy friend, but not thy vices' friend.",
"False friends are worse than open enemies.", 
"Short acquaintance brings repentance.", 
"He that lies down (sleeps) with dogs must rise up with fleas.", 
"Better be alone than in bad company.", 
"Write down the advice of him who loves you, though you like it not at present.",
"Hunger knows no friend.", 
"Misery makes strange bedfellows.", 
"One enemy can do more hurt than ten friends can do good.", 
"An enemy's mouth seldom speaks well.", 
"Believe no tales from the enemy.", 
"One enemy is too much.", 
"Mickle power makes many enemies.", 
"Do not despise your enemy.", 
"Though thy enemy seem a mouse, yet watch him like a lion.",
"If we are bound to forgive an enemy, we are not bound to trust him.",
"He that dallies with enemy gives him leave to kill him.", 
"In an enemy spots are soon seen.", 
" If you would make an enemy, lend a man money and ask it of him again.",
" A courageous foe is better than a cowardly friend.", 
" An enemy who lies at thy feet begging forgi-veness must not feel thy sword.", 
" Make your enemy your friend.", 
" Live and let live.", 
" As a man lives, so shall he die.",
" We are not born for ourselves.", 
" He that hath time hath life.", 
" He that lives long suffers much.", 
" They who live longest will see most.", 
"He was born with a silver spoon in his mouth.", 
"A man can die but once.", 
"He that liveth in court dieth upon straw.", 
"He that liveth wickedly can hardly die honestly.", 
"Death pay all debts.", 
"Six feet of earth makes all men equal.", 
"Death is the grand leveller.", 
"Death meets us everywhere.", 
"Death frees us from ills.", 
"We shall lie all alike in our graves.", 
"In the grave the rich and poor lie equal.", 
"Death defies the doctor.", 
"There is no medicine against death.", 
"Light come, light go.",
"Sometimes gain is to lose.", 
"Merry is he that hath nought to lose.", 
"Grasp all, lose all.",
"What we lose in hake we shall have in herring.", 
"What is lost in the hundred will be found in the shire.", 
"For a lost thing care nothing.", 
"He who does not gain loses.", 
"Losses make us more cautious.", 
"Who loseth liberty loseth all.", 
"Either win the horse or lose the saddle.", 
"All is not lost that is in danger.", 
"Do not run too fast after gain.", 
"Prefer loss to unjust gain.", 
"Lightly gain, quickly lost.",
"Only that which is honestly got is gain.", 
"All is not gain that is put in the purse.", 
"Gain got by a lie will burn one's fingers.", 
"One never loses anything by politeness.", 
"Hold fast when you have it.", 
"There are as good fish in the sea as ever came out of it.", 
"Many a slip (many things fall) between the cup and the lip.", 
"It is an ill wind that blows nobody good.", 
"Health is better than wealth.", 
"Health is happiness.", 
"A good healthy body is worth more a crown in gold.", 
"A sound mind in a sound body.", 
"A light heart lives long.", 
"A happy heart makes a blooming visage.", 
"He who hath good health is young, and he is rich who owes nothing.",
"Study sickness while you are well.", 
"The healthful man can give counsel to the sick.", 
"By the side of sickness health becomes sweet.", 
"Health is not valued till sickness comes.", 
"Feed by measure and defy physician.", 
"Often and little eating makes a man fat.", 
"After dinner sit awhile, after supper walk a mile.",
"Early to bed and early to rise, makes a man healthy,wealthy and wise.",
"He that will thrive must rise at five.", 
"He that goes to bed thirsty rises healthy.", 
"He who does not rise early never does a good day's work.", 
"Who makes everything right must rise early.", 
"Go to bed with the lamb and rise with the lark.", 
"Cover your head by day as much as you will, by night as much as you can.",
"A little labour, much health.",
"Enough is as good as a feast.", 
"Many dishes, many diseases.",
"Diseases are the Price of ill pleasures.", 
"Desperate diseases must have desperate cures.", 
"He who never was sick dies the first.", 
"Sickness shows us what we are.", 
"What can't be cured must be endured.", 
"Hide nothing from thy physician.", 
"Medicines are not meant to live on.", 
"A disease known is half cured.", 
"The best physicians are Dr. Diet,  Dr. Quiet,and Dr. Merryman.",
"A good surgeon must have an eagle's eye, a lion's heart,and a lady's hand.",
"Feed sparingly and defy the physician.", 
"Prevention is better than cure.", 
"An ounce of prevention is worth a pound of cure.", 
"Bitter pills may have wholesome effect.", 
"A good medicine tastes bitter.", 
"There is no friend so faithful as a good book.", 
"Books, like friends,should be few and well chosen.",
"A book is the same today as it always was and it will never change.", 
"A good book is a best friend who never turns his back upon us.", 
"In books, are embalmed the greatest thoughts of all ages.",
"Some books are to be tasted, others to be swallowed,and some few to be chewed and digested.",
"Old wood is best to burn, old book to read.",
"A book that remains shut is but a block.", 
"Judge not a book by its cover.", 
"A wicked book is the wickeder because it cannot repent.", 
"A good tale is none the worse for being twice told.", 
"Law is a bottomless pit.", 
"Ignorance of the law excuses no man.", 
"Law makers should not be law breakers.", 
"Wrong laws make short governance.", 
" The law is not the same at morning and at night.", 
" New lords, new laws.",
" Laws catch flies and let hornets go free.", 
" Where drums beat, laws are silent.",
" An upright judge has more regard to justice than to men.", 
" That trial is not fair where affection is the judge.", 
" A good lawyer, an evil neighbour.",
" An old physician, and a young lawyer.",
" Do not count your chickens before they are hatched.", 
" Though the fox run, the chicken hath wings.",
"Young cocks love no coops.", 
"A cock is bold on his dunghill.", 
"A barley-corn is better than a diamond to a cock.", 
"He that will have his farm full, must keep an old cock and a young bull.",
"If the hen does not prate, she will not lay.",
"It is no good hen that cackles in your house and lays in another's.", 
"Fat hens lay few eggs.", 
"Grain by grain, and the hen fills her belly.",
"A duck will not always dabble in the same gutter.", 
"It is a blind silly gooes that comes to the fox's sermon.", 
"What is sauce for the goose is sauce for the gander.", 
"All his geese are swans.", 
"All your swans are geese.", 
"Each bird likes to hear himself sing.", 
"The bird loves her nest.", 
"Birds of a feather flock together.", 
"The bird that can sing and won't sing must be made to sing.", 
"The fowler's pipe sounds sweet until the bird is caught.", 
"He that will take the bird must not scare it.", 
"The noisy fowler catches no bird.", 
"Old birds are not caught with new nests.", 
"'Tis the early bird that catches the worm.", 
"A bird in the hand is worth two in the bush.", 
"A bird is known by its note, and a man by his talk.",
"It is an ill bird that fouls its own nest.", 
"Eagles fly alone, but sheep flock together.",
"A kite will never be a good hawk.", 
"Empty hands no hawk allure.", 
"The crow thinks his own bird fairest.", 
"A crow is never the whiter for washing herself often.", 
"Wheresoever the carcase is,  there will the ravens be gathered together.",
"One swallow does not make a summer.", 
"The snail slides up the tower at last though the swallow mounteth it sooner.", 
"The cuckoo comes in April, and stays the month of May;sings a song at Midsummer,and then goes away.",
"If the sky falls, we shall catch larks.",
"An owl is the king of the night.", 
"When the owl sings, the nightingale will hold her peace.",
"Cats hide their paws.", 
"A gloved cat catches no mice.", 
"When the cat's away, the mice will play.",
"Ale will make cat speak.", 
"A blate cat makes a proud mouse.", 
"When the weasel and the cat make a marriage, it is a very ill presage.",
"The cat and dog may kiss, yet are none the better friends.",
"All cats love fish but fear to wet their paws.", 
"A cat may look at a king.", 
"It is said that \"cat hath nine lives\", yet care would wear them all out.",
"An old dog bites sore.", 
"Beware of a silent dog and still water.", 
"Barking dogs seldom bite.", 
"A dog will not howl if you beat him with a bone.", 
"Dogs that bark at a distance bite not at hand.", 
"If the old dog barks, he gives counsel.",
"In every country dogs bite.", 
"Hungry dogs will eat dirty puddings.", 
"Dogs wag their tails not so much in love to you as your bread.", 
"All are not thieves that dogs bark at.", 
"Every dog is valiant at his own door.", 
"Every dog is a lion at home.", 
"While the dog gnaws bone, companions would be none.",
"Two dogs strive for a bone, the third runs away with it.",
"Mad dog bites his master.", 
"Too much pudding will choke dog.", 
"Do not give a dog bread every time he wags his tail.", 
"A living dog is better than a dead lion.", 
"Love me, love my dog.",
"Let sleeping dog lie.", 
"Help the dog over the stile.", 
"Every dog has his day.", 
"Give a dog a bad name and hang him.", 
"He who has a mind to beat his dog will easily find a stick.", 
"An old dog cannot alter its way of barking.", 
"When a dog is drowning, every one offers him drink.",
"A swine over fat is the cause of his own bane.", 
"Pigs may fly, but they are very unlikely birds.",
"Never cast your pearls before swine.", 
"You cannot make a silk purse out of a sow's ear.", 
"The cow that's first up gets the first of the dew.", 
"Not all butter that the cow yields.", 
"Many good cows have evil calves.", 
"You cannot sell the cow and sup the milk.", 
"Old oxen have stiff horns.", 
"The ox is never woe, till he to the harrow go.",
"An ox is taken by the horns, and the man by the tongue.",
"If the ox falls, whet your knife.",
"The black ox has trod on his foot.", 
"The ox when weariest treads surest.", 
"The best horse needs breaking, and the aptest child needs teaching.",
"A horse that will not carry a saddle must have no oats.", 
"A good horse oft needs a good spur.", 
" It is the bridle and spur that makes a good horse.", 
" A boisterous horse must have a rough bridle.", 
" He is a gentle horse that never cast his rider.", 
" 'Tis a good horse that never stumbles.", 
" The fault of the horse is put on the saddle.", 
" Mettle is dangerous in a blind horse.", 
" Old wood is best to burn, old horse to ride.",
" Every horse thinks his sack heaviest.", 
" You may know the horse by his harness.", 
" A galled horse will not endure the comb.", 
"You can take a horse to the water, but you cannot make him drink.",
"Don't swap horses when crossing a stream.", 
"An ass endures his burden, but not more than his burden.",
"Wherever an ass falleth, there will he never fall again.",
"The braying of an ass does not reach heaven.", 
"The fault of the ass must not be laid upon the packsaddle.", 
"A horse is neither better nor worse for his trappings.", 
"He who wants a mule without fault, must walk on foot.",
"A colt you may break, but an old horse you never can.",
"One sheep follows another.", 
"If one sheep leap o'er the dyke, all the rest will follow.",
"There is a black sheep in every flock.", 
"One scabbed sheep will mar a whole flock.", 
"Every time the sheep bleats it loses a mouthful.", 
"One butcher does not fear many sheep.", 
"It is a foolish sheep that makes the wolf his confessor.", 
"The dust raised by the sheep does not choke the wolf.", 
"Carrion crows bewail the dead sheep and then eat them.", 
"The life of the wolf is the death of the lamb.", 
"As soon goes the young lamb's skin to the market as the old ewe's.", 
"You have no goats, and yet you sell kids.",
"If the beard were all, the goat might preach.",
"A lazy sheep thinks its wool heavy.", 
"He that will have a hare to breakfast must hunt overnight.", 
"If you run after two hares, you will catch neither.",
"One should not run with the hare and hunt with the hounds.", 
"The tortoise wins the race while the hare is sleeping.", 
"First catch your hare then cook him.", 
"The fox is known by his brush.", 
"The fox smells his own stink first.", 
"The fox may grow grey,  but never good.",
"The tail does often catch the fox.", 
"It is an evil sign to see a fox lick a lamb.", 
"When the fox preacheth, then beware your geese.",
"An old fox is not easily snared.", 
"Old foxes want no tutors.", 
"The sleeping fox catches no poultry.", 
"You can have no more of the fox than the skin.", 
"The fox that had lost its tail would persuade others out of theirs.", 
"A fox should not be of the jury at a goose's trial.", 
"The fox's wiles will never enter the lion's head.", 
"The old goose plays not with foxes.", 
"The wolf and fox are both privateers.", 
"The wolf may lose his teeth,  but never his nature.",
"A thief knows a thief as a wolf knows a wolf.", 
"Hunger fetches the wolf out of the woods.", 
"Give never the wolf the wether.", 
"Who keeps company with the wolf will learn to howl.", 
"The lone sheep is in danger of the wolf.", 
"It is madness for a sheep to treat of peace with a wolf.", 
"By little and little the wolf eateth the sheep.", 
"The death of wolves is the safety of the sheep.", 
"While you trust to the dog, the wolf slips into the sheepfold.",
"When the wolf grows old,  the crows ride him.",
"Man is to man either a god or a wolf.", 
"A growing youth has a wolf in his belly.", 
"The lion is known by his claws (paw).", 
"The lion is not so fierce as he is painted.", 
"A barking dog is better than a sleeping lion.", 
"It is not good to wake a sleeping lion.", 
"The lion's skin is never cheap.", 
"Destroy the lion while he is yet but a whelp.", 
"The tiger that has once tasted blood is never sated with the taste of it.", 
"He who rides a tiger is afraid to dismount.", 
"The leopard can never change its spots.", 
"Kings and bears oft worry keepers.", 
"He who shareth honey with the bear hath the least part of it.", 
"Do not sell the bear's skin before you have caught the bear.", 
"Where the deer is slain, some of her blood will lie.",
"The rage of a wild boar is able to spoil more than one wood.", 
"An ape's an ape,  a varlet's a varlet, though they be clad in silk or scarlet.",
"An army of stags led by a lion would be more formidable than one of lions led by a stag.", 
"A bad custom is like a good cake,  better broden than kept.",
"A bald head is soon shaven.", 
"A blind man will not thank you for a looking-glass.", 
"A borrowed cloak does not keep one warm.", 
"A brave retreat is a brave exploit.", 
"Accidents will happen in the best regulated families.", 
"A candle lights others and consumes itself.", 
"A constant guest is never welcome.", 
"A cracked bell can never sound well (is never sound).", 
"A crown is no cure for the headache.", 
"A drowning man will catch at a straw.", 
"After a storm comes a calm.", 
"After death,  the doctor.",
"A good beginning is half done.", 
"A good example is the best sermon.", 
"A great ship asks deep waters.", 
"A horse stumbles that has four legs.", 
"A little neglect may breed great mischief.", 
" A little pot is soon hot.", 
" All are brave when the enemy flies.", 
" All is fish that comes to his net.", 
" All is well that ends well.", 
" All roads lead to Rome.", 
" Always taking out the meal-tub,  and never putting in,soon comes to the bottom.",
" A miss is as good as a mile.", 
" An empty bag cannot stand upright.", 
" A new broom sweeps clean.", 
" A rolling stone gathers no moss.", 
"Art is long,  life is short.",
"A small leak will sink a great ship.", 
"A stitch in time saves nine.", 
"As the wind blows,  you must set your sail.",
"As we sow,  so shall we reap.",
"A valiant man's look is more than a coward's sword.", 
"A vaunter and a liar are near akin.", 
"Avarice blinds our eyes.", 
"A watched pot(pan) is long in boiling.", 
"A wonder lasts but nine days.", 
"Beard the lion in his den.", 
"Beauty is but skin deep.", 
"Better be the head of a dog than the tail of a lion.", 
"Better be the head of the yeomanry than the tail of the gentry.", 
"Between two stools one goes the ground.", 
"Beware beginnings.", 
"Blood is thicker than water.", 
"Caesar's wife must be above suspicion.", 
"Charity begins at home,  but should not end there.",
"Companions are odious.", 
"Content is happiness.", 
"Custom is a second nature.", 
"Cut your coat according to your cloth.", 
"Danger is next neighbour to security.", 
"Do as the Romans do.", 
"Do as you would be done by.", 
"Do not hallo till you are out of the wood.", 
"Don't put the cart before the horse.", 
"Don't throw out the baby with the bath water.", 
"Envy assails the noblest,  the winds howl around the highest peak.",
"Every advantage has its disadvantage.", 
"Every cloud has a silver lining.", 
"Every man has his liking.", 
"Every one's faults are not written in their foreheads.", 
"Everything hath an end.", 
"Everything must have a beginning.", 
"Example is better than precept.", 
"Fine feathers make fine birds.", 
"Fire and water have no mercy.", 
"First come,  first served.",
"Fish begins to stink at the head.", 
"Forbidden fruit is sweet.", 
"Force can never destory right.", 
"God's mill grinds slow but sure.", 
"Great designs require great consideration.", 
"Great men have great faults.", 
"Great men's sons seldom do well.", 
"Half a loaf is better than no bread.", 
"Haste makes waste.", 
"Hear all parties.", 
"He laughs best who laughs last.", 
"He measures another's corn by his own bushel.", 
"He should have a long spoon that sups with the devil.", 
"He that never rode never fell.", 
"He that would eat the kernel must crack the nut.", 
"History repeats itself.", 
"Hoist your sail when the wind is fair.", 
"Honey is sweet,  but the bee stings.",
"Hunger is the best sauce.", 
"If the mountain will not come to Mahomet, Mahomet must go to the mountain.",
"If wishes were horses, beggars might ride.",
"Ill air slays sooner than the sword.", 
"Ill news never comes too late.", 
"In the kingdom of blind men,  the oneeyed is king.",
"It is better to be a martyr than a confessor.", 
"It is too late to shut the stalbe door when the steed is stolen.", 
"It never rains but it pours.", 
"It takes two to make a quarrel.", 
"Jack of all trades and master of none.", 
"Joy and sorrow are next-door neighbours.", 
"Keeping is harder than winning.", 
"Kill the goose that lays the golden eggs.", 
"Kill two birds with one stone.", 
"Kinsman helps kinsman,  but woe to him that hath nothing.",
"Like tree,  like fruit.",
"Little thieves are hanged,  but great ones escape.",
"Long absent,  soon forgotten.",
"Long looked for comes at last.", 
"Long tarrying takes all thands away.", 
"Losers are always in the wrong.", 
"Man is a god or a devil to his neighbour.", 
"Many men have many minds.", 
"Many wells,  many buckets.",
"Mercy to the eriminal may be eruelty to the people.", 
"Merry meet,  merry part.",
"Messengers should neither be headed nor hanged.", 
"Might is right.", 
"Might overcomes right.", 
"Mischief has swift wings.", 
"Misery loves company.", 
" Mock not a cobbler for his black thumbs.", 
" Most things have two handles.", 
" Music is the eye of the ear.", 
" Necessity and opportunity may make a coward valiant.", 
" Necessity is the mother of invention.", 
" Neither fish nor flesh (nor good red herring).", 
" Never judge from appearances.", 
" Never too late to mend.", 
" No cross,  no crown.",
" No man can do two things at once.", 
"No man ever became thoroughly bad all at once.", 
"No man is content.", 
"No mill,  no meal.",
"No pleasure without pain.", 
"No rose without a thorn.", 
"No smoke without some fire.", 
"Nothing venture,  nothing have.",
"Obedience is the first duty of a soldier.", 
"Older and wiser.", 
"Old bees yield no honey.", 
"Old vessels must leak.", 
"Once a devil,  always a devil.",
"One flower makes no garland.", 
"One foot is better than two crutches.", 
"Oppression maketh a wise man mad.", 
"Out of sitght,  out of mind.",
"Pain is forgotten where gain follows.", 
"Patience is the plaster of all sores.", 
"Patient men win the day.", 
"Peace with sword in hand,  'Tis safest making.",
"Pen and ink is wit's plough.", 
"Penny wise and pound foolish.", 
"Poison is poison though it comes in a golden cup.", 
"Pouring oil on the fire is no way to quench it.", 
"Praise is not pudding.", 
"Promises are like piecrust,  made to be broken.",
"Promise is debt.", 
"Public money is like holy water,  every one helps himself to it.",
"Quietness is best.", 
"Rain before seven: fine before eleven.", 
"Reading maketh a full man,  conference a ready man, and writing an  exact man.",
"Remember thou art but a man.", 
"Revolutions are not made with rosewater.", 
"Satan reproves sin.", 
"Scanderbeg's sword must have Scanderbeg's arm.", 
"Shallow streams make most din.", 
"Short pleasure,  long lament.",
"Silence gives consent.", 
"Skill and confidence are an unconquered army.", 
"Something is better than nothing.", 
"Soon ripe,  soon rotten.",
"Sorrow comes unsent for.", 
"Sport is sweetest when there be no spectators.", 
"Still waters run deep.", 
"Straws show which way the wind blows.", 
"Talk of the devil,  and he is sure to appear.",
"Teach your grandmother to suck eggs.", 
"Temperance is the best physic.", 
"The best (greatest) fish keep (swim near) the bottom.", 
"The best is oftentimes the enemy of the good.", 
"The mountains have brought forth a mouse.", 
"The pot calls the kettle black.", 
"There are two sides to every question.", 
"There is a crook(=affliction,  trial) in the lot of every one.",
"The swan sings when death comes.", 
"The thread breaks where it is weakest.", 
"The tongue ever turns to the aching teeth.", 
"The used key is always bright.", 
"The weakest goes to the wall.", 
"The wish is father to the thought.", 
"Things done cannot be undone.", 
"Things unreasonable are never durable.", 
"Too many cooks spoil the broth.", 
"Too much liberty spoils all.", 
"Too much spoils,  too little is nothing.",
"Tread on a worm and it will turn.", 
"True praise roots and spreads.", 
"Two of a trade seldom agree.", 
"Two wrongs don't make a right.", 
"Union is strength.", 
"Vain glory blossoms but never bears.", 
"Vows made in storms are forgotten in calms.", 
"Walls have ears.", 
"War is death's feast.", 
"War makes thieves,  and peace hangs them.",
"Water afar quencheth not fire.", 
"Weeds want no sowing.", 
"We never know the worth of water till the well is dry.", 
"What youth is used to,  age remembers.",
"When Greek meets Greek,  then comes the bug of war.",
"When the tree is fallen,  every one runs to it with his axe.",
"When the well is full,  it will run over.",
"When war begins, then hell openeth.",
"Where there are reeds,  there is water.",
"Where there is a will,  there is a way.",
"Where the water is shallow,  no vessel will ride.",
"Who swims in sin shall sink in sorrow.", 
"Wine in the bottle does not quench thirst.", 
"Woe to him that is alone.", 
"You cannot see the wood for trees."};
#define QuotesCount (sizeof(Quotes)/sizeof(char *)) 
#endif